version: '3'
services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
#  db:
#     image: mysql
#     container_name: mysql_db
#     restart: always
#     environment:
#        - MYSQL_ROOT_PASSWORD="secret"
# web:
#   image: apache
#   build: ./webapp
#   depends_on:
#      - db
#   container_name: apache_web
#   restart: always
#   ports:
#     - "8080:80"
#  db:
#     image: mysql
#     container_name: mysql_db
#     restart: always
#     environment:
#        - MYSQL_ROOT_PASSWORD="secret"
